
const candidats = [
  {
    cin: "AB123456",
    nom: "Boushaba",
    prenom: "Soufiane",
    partiPolitique: "Parti Authenticite et Modernite",
    age: 40,
    electeurs: ["DD993456" ,"NN23456" ,"AB323456" ],
  },
  {
    cin: "BS123456",
    nom: "samir",
    prenom: "Samor",
    partiPolitique: "Parti Authenticite et Modernite",
    age: 30,
    electeurs: ["MM88456" ,"KJ663456"],
  },
  {
    cin: "BB423456",
    nom: "boushak",
    prenom: "amin",
    partiPolitique: "Rassemblement National des Independants",
    age: 20,
    electeurs: ["AB963456"],
  },
  {
    cin: "AA12346",
    nom: "aymen",
    prenom: "amin",
    partiPolitique: "Rassemblement National des Independants",
    age: 50,
    electeurs: [],
  },
  {
    cin: "KK123456",
    nom: "soulaimane",
    prenom: "salim",
    partiPolitique: "Mouvement Populaire",
    age: 20,
    electeurs: ["CC123456" , "FF453456"],
  },
  {
    cin: "LL753456",
    nom: "samir",
    prenom: "daw",
    partiPolitique: "Mouvement Populaire",
    age: 30,
    electeurs: [],
  },
  {
    cin: "DD993456",
    nom: "bouadi",
    prenom: "Soufiane",
    partiPolitique: "Indépendant",
    age: 60,
    electeurs: [],
  },
  {
    cin: "NN23456",
    nom: "labib",
    prenom: "anas",
    partiPolitique: "Indépendant",
    age: 40,
    electeurs: [],
  },
  {
    cin: "AB323456",
    nom: "mohamed",
    prenom: "hanin",
    partiPolitique: "Indépendant",
    age: 25,
    electeurs: [],
  },
  {
    cin: "KJ663456",
    nom: "walid",
    prenom: "khawa",
    partiPolitique: "Indépendant",
    age: 60,
    electeurs: [],
  },
  {
    cin: "MM88456",
    nom: "senani",
    prenom: "sakaria",
    partiPolitique: "Indépendant",
    age: 40,
    electeurs: [],
  },
  {
    cin: "AB963456",
    nom: "hamada",
    prenom: "adam",
    partiPolitique: "Indépendant",
    age: 29,
    electeurs: [],
  },
  {
    cin: "CC123456",
    nom: "Boushaba",
    prenom: "oussama",
    partiPolitique: "Indépendant",
    age: 47,
    electeurs: [],
  },
  {
    cin: "FF453456",
    nom: "hamami",
    prenom: "ayoub",
    partiPolitique: "Indépendant",
    age: 43,
    electeurs: [],
  },
  
];



console.log(candidats);